#!/usr/bin/env sh

# remote node config (rnode1)
rnodeVer=dev;
grpcHost=rnode1;
grpcPort=50511;

# execute rnode command
docker run -it --rm --network rchainnetwork_rchain-net -v $PWD/contracts:/contracts rchain/rnode:$rnodeVer --grpc-host $grpcHost -g $grpcPort $*
